package vavi.awt.image.jna.jpegxl;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : jxl/codestream_header.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class JxlAnimationHeader extends Structure {
	public int tps_numerator;
	public int tps_denominator;
	public int num_loops;
	public int have_timecodes;
	public JxlAnimationHeader() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("tps_numerator", "tps_denominator", "num_loops", "have_timecodes");
	}
	public JxlAnimationHeader(int tps_numerator, int tps_denominator, int num_loops, int have_timecodes) {
		super();
		this.tps_numerator = tps_numerator;
		this.tps_denominator = tps_denominator;
		this.num_loops = num_loops;
		this.have_timecodes = have_timecodes;
	}
	public JxlAnimationHeader(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends JxlAnimationHeader implements Structure.ByReference {
	}
	public static class ByValue extends JxlAnimationHeader implements Structure.ByValue {
	}
}
