package vavi.awt.image.jna.jpegxl;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : jxl/codestream_header.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class JxlBlendInfo extends Structure {
	/**
	 * @see Library.JxlBlendMode
	 * C type : JxlBlendMode
	 */
	public int blendmode;
	public int source;
	public int alpha;
	public int clamp;
	public JxlBlendInfo() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("blendmode", "source", "alpha", "clamp");
	}
	/**
	 * @param blendmode @see JxlBlendMode<br>
	 * C type : JxlBlendMode
	 */
	public JxlBlendInfo(int blendmode, int source, int alpha, int clamp) {
		super();
		this.blendmode = blendmode;
		this.source = source;
		this.alpha = alpha;
		this.clamp = clamp;
	}
	public JxlBlendInfo(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends JxlBlendInfo implements Structure.ByReference {
	}
	public static class ByValue extends JxlBlendInfo implements Structure.ByValue {
	}
}
