package vavi.awt.image.jna.jpegxl;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : jxl/cms_interface.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class JxlColorProfile extends Structure {
	/** C type : icc_struct */
	public icc_struct icc;
	/** C type : JxlColorEncoding */
	public JxlColorEncoding color_encoding;
	public NativeLong num_channels;
	/** <i>native declaration : jxl/cms_interface.h:10</i> */
	public static class icc_struct extends Structure {
		/** C type : const uint8_t* */
		public Pointer data;
		public NativeLong size;
		public icc_struct() {
		}
		protected List<String> getFieldOrder() {
			return Arrays.asList("data", "size");
		}
		/** @param data C type : const uint8_t* */
		public icc_struct(Pointer data, NativeLong size) {
			this.data = data;
			this.size = size;
		}
		public icc_struct(Pointer peer) {
			super(peer);
		}
		public static class ByReference extends icc_struct implements Structure.ByReference {
		}
		public static class ByValue extends icc_struct implements Structure.ByValue {
		}
	}
	public JxlColorProfile() {
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("icc", "color_encoding", "num_channels");
	}
	/**
	 * @param icc C type : icc_struct<br>
	 * @param color_encoding C type : JxlColorEncoding
	 */
	public JxlColorProfile(icc_struct icc, JxlColorEncoding color_encoding, NativeLong num_channels) {
		this.icc = icc;
		this.color_encoding = color_encoding;
		this.num_channels = num_channels;
	}
	public JxlColorProfile(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends JxlColorProfile implements Structure.ByReference {
	}
	public static class ByValue extends JxlColorProfile implements Structure.ByValue {
	}
}
