package vavi.awt.image.jna.jpegxl;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : jxl/codestream_header.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class JxlFrameHeader extends Structure {
	public int duration;
	public int timecode;
	public int name_length;
	public int is_last;
	/** C type : JxlLayerInfo */
	public JxlLayerInfo layer_info;
	public JxlFrameHeader() {
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("duration", "timecode", "name_length", "is_last", "layer_info");
	}
	/** @param layer_info C type : JxlLayerInfo */
	public JxlFrameHeader(int duration, int timecode, int name_length, int is_last, JxlLayerInfo layer_info) {
		this.duration = duration;
		this.timecode = timecode;
		this.name_length = name_length;
		this.is_last = is_last;
		this.layer_info = layer_info;
	}
	public JxlFrameHeader(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends JxlFrameHeader implements Structure.ByReference {
	}
	public static class ByValue extends JxlFrameHeader implements Structure.ByValue {
	}
}
