package vavi.awt.image.jna.jpegxl;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;

import java.util.Collections;
import java.util.List;
/**
 * <i>native declaration : jxl/codestream_header.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class JxlHeaderExtensions extends Structure {
	public long extensions;
	public JxlHeaderExtensions() {
	}
	protected List<String> getFieldOrder() {
		return Collections.singletonList("extensions");
	}
	public JxlHeaderExtensions(long extensions) {
		this.extensions = extensions;
	}
	public JxlHeaderExtensions(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends JxlHeaderExtensions implements Structure.ByReference {
	}
	public static class ByValue extends JxlHeaderExtensions implements Structure.ByValue {
	}
}
