package vavi.awt.image.jna.jpegxl;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : jxl/codestream_header.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class JxlLayerInfo extends Structure {
	public int have_crop;
	public int crop_x0;
	public int crop_y0;
	public int xsize;
	public int ysize;
	/** C type : JxlBlendInfo */
	public JxlBlendInfo blend_info;
	public int save_as_reference;
	public JxlLayerInfo() {
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("have_crop", "crop_x0", "crop_y0", "xsize", "ysize", "blend_info", "save_as_reference");
	}
	/** @param blend_info C type : JxlBlendInfo */
	public JxlLayerInfo(int have_crop, int crop_x0, int crop_y0, int xsize, int ysize, JxlBlendInfo blend_info, int save_as_reference) {
		this.have_crop = have_crop;
		this.crop_x0 = crop_x0;
		this.crop_y0 = crop_y0;
		this.xsize = xsize;
		this.ysize = ysize;
		this.blend_info = blend_info;
		this.save_as_reference = save_as_reference;
	}
	public JxlLayerInfo(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends JxlLayerInfo implements Structure.ByReference {
	}
	public static class ByValue extends JxlLayerInfo implements Structure.ByValue {
	}
}
