package vavi.awt.image.jna.jpegxl;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : jxl/codestream_header.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class JxlPreviewHeader extends Structure {
	public int xsize;
	public int ysize;
	public JxlPreviewHeader() {
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("xsize", "ysize");
	}
	public JxlPreviewHeader(int xsize, int ysize) {
		this.xsize = xsize;
		this.ysize = ysize;
	}
	public JxlPreviewHeader(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends JxlPreviewHeader implements Structure.ByReference {
	}
	public static class ByValue extends JxlPreviewHeader implements Structure.ByValue {
	}
}
