package vavi.awt.image.jna.jpegxl;

import com.sun.jna.Callback;
import com.sun.jna.Native;
import com.sun.jna.NativeLibrary;
import com.sun.jna.Pointer;


/**
 * JNA Wrapper for library <b></b><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public interface Library extends com.sun.jna.Library {
	String JNA_LIBRARY_NAME = "";
	NativeLibrary JNA_NATIVE_LIB = NativeLibrary.getInstance(Library.JNA_LIBRARY_NAME);
	Library INSTANCE = Native.load(Library.JNA_LIBRARY_NAME, Library.class);
	/**
	 * <i>native declaration : jxl/types.h</i><br>
	 * enum values
	 */
	interface JxlDataType {
		/** <i>native declaration : jxl/types.h:25</i> */
		int JXL_TYPE_FLOAT = 0;
		/** <i>native declaration : jxl/types.h:31</i> */
		int JXL_TYPE_BOOLEAN = 1;
		/** <i>native declaration : jxl/types.h:35</i> */
		int JXL_TYPE_UINT8 = 2;
		/** <i>native declaration : jxl/types.h:39</i> */
		int JXL_TYPE_UINT16 = 3;
		/** <i>native declaration : jxl/types.h:43</i> */
		int JXL_TYPE_UINT32 = 4;
		/** <i>native declaration : jxl/types.h:46</i> */
		int JXL_TYPE_FLOAT16 = 5;
	};
	/**
	 * <i>native declaration : jxl/types.h</i><br>
	 * enum values
	 */
	interface JxlEndianness {
		/** <i>native declaration : jxl/types.h:56</i> */
		int JXL_NATIVE_ENDIAN = 0;
		/** <i>native declaration : jxl/types.h:58</i> */
		int JXL_LITTLE_ENDIAN = 1;
		/** <i>native declaration : jxl/types.h:60</i> */
		int JXL_BIG_ENDIAN = 2;
	};
	/**
	 * <i>native declaration : jxl/color_encoding.h</i><br>
	 * enum values
	 */
	interface JxlColorSpace {
		/** <i>native declaration : jxl/color_encoding.h:25</i> */
		int JXL_COLOR_SPACE_RGB = 0;
		/** <i>native declaration : jxl/color_encoding.h:29</i> */
		int JXL_COLOR_SPACE_GRAY = 1;
		/** <i>native declaration : jxl/color_encoding.h:31</i> */
		int JXL_COLOR_SPACE_XYB = 2;
		/** <i>native declaration : jxl/color_encoding.h:33</i> */
		int JXL_COLOR_SPACE_UNKNOWN = 3;
	};
	/**
	 * <i>native declaration : jxl/color_encoding.h</i><br>
	 * enum values
	 */
	interface JxlWhitePoint {
		/** <i>native declaration : jxl/color_encoding.h:40</i> */
		int JXL_WHITE_POINT_D65 = 1;
		/** <i>native declaration : jxl/color_encoding.h:42</i> */
		int JXL_WHITE_POINT_CUSTOM = 2;
		/** <i>native declaration : jxl/color_encoding.h:44</i> */
		int JXL_WHITE_POINT_E = 10;
		/** <i>native declaration : jxl/color_encoding.h:46</i> */
		int JXL_WHITE_POINT_DCI = 11;
	};
	/**
	 * <i>native declaration : jxl/color_encoding.h</i><br>
	 * enum values
	 */
	interface JxlPrimaries {
		/** <i>native declaration : jxl/color_encoding.h:54</i> */
		int JXL_PRIMARIES_SRGB = 1;
		/** <i>native declaration : jxl/color_encoding.h:57</i> */
		int JXL_PRIMARIES_CUSTOM = 2;
		/** <i>native declaration : jxl/color_encoding.h:59</i> */
		int JXL_PRIMARIES_2100 = 9;
		/** <i>native declaration : jxl/color_encoding.h:61</i> */
		int JXL_PRIMARIES_P3 = 11;
	};
	/**
	 * <i>native declaration : jxl/color_encoding.h</i><br>
	 * enum values
	 */
	interface JxlTransferFunction {
		/** <i>native declaration : jxl/color_encoding.h:68</i> */
		int JXL_TRANSFER_FUNCTION_709 = 1;
		/** <i>native declaration : jxl/color_encoding.h:70</i> */
		int JXL_TRANSFER_FUNCTION_UNKNOWN = 2;
		/** <i>native declaration : jxl/color_encoding.h:72</i> */
		int JXL_TRANSFER_FUNCTION_LINEAR = 8;
		/** <i>native declaration : jxl/color_encoding.h:74</i> */
		int JXL_TRANSFER_FUNCTION_SRGB = 13;
		/** <i>native declaration : jxl/color_encoding.h:76</i> */
		int JXL_TRANSFER_FUNCTION_PQ = 16;
		/** <i>native declaration : jxl/color_encoding.h:78</i> */
		int JXL_TRANSFER_FUNCTION_DCI = 17;
		/** <i>native declaration : jxl/color_encoding.h:80</i> */
		int JXL_TRANSFER_FUNCTION_HLG = 18;
		/** <i>native declaration : jxl/color_encoding.h:83</i> */
		int JXL_TRANSFER_FUNCTION_GAMMA = 65535;
	};
	/**
	 * <i>native declaration : jxl/color_encoding.h</i><br>
	 * enum values
	 */
	interface JxlRenderingIntent {
		/** <i>native declaration : jxl/color_encoding.h:89</i> */
		int JXL_RENDERING_INTENT_PERCEPTUAL = 0;
		/** <i>native declaration : jxl/color_encoding.h:91</i> */
		int JXL_RENDERING_INTENT_RELATIVE = 1;
		/** <i>native declaration : jxl/color_encoding.h:93</i> */
		int JXL_RENDERING_INTENT_SATURATION = 2;
		/** <i>native declaration : jxl/color_encoding.h:95</i> */
		int JXL_RENDERING_INTENT_ABSOLUTE = 3;
	};
	/**
	 * <i>native declaration : jxl/codestream_header.h</i><br>
	 * enum values
	 */
	interface JxlOrientation {
		/** <i>native declaration : jxl/codestream_header.h:12</i> */
		int JXL_ORIENT_IDENTITY = 1;
		/** <i>native declaration : jxl/codestream_header.h:13</i> */
		int JXL_ORIENT_FLIP_HORIZONTAL = 2;
		/** <i>native declaration : jxl/codestream_header.h:14</i> */
		int JXL_ORIENT_ROTATE_180 = 3;
		/** <i>native declaration : jxl/codestream_header.h:15</i> */
		int JXL_ORIENT_FLIP_VERTICAL = 4;
		/** <i>native declaration : jxl/codestream_header.h:16</i> */
		int JXL_ORIENT_TRANSPOSE = 5;
		/** <i>native declaration : jxl/codestream_header.h:17</i> */
		int JXL_ORIENT_ROTATE_90_CW = 6;
		/** <i>native declaration : jxl/codestream_header.h:18</i> */
		int JXL_ORIENT_ANTI_TRANSPOSE = 7;
		/** <i>native declaration : jxl/codestream_header.h:19</i> */
		int JXL_ORIENT_ROTATE_90_CCW = 8;
	};
	/**
	 * <i>native declaration : jxl/codestream_header.h</i><br>
	 * enum values
	 */
	interface JxlExtraChannelType {
		/** <i>native declaration : jxl/codestream_header.h:25</i> */
		int JXL_CHANNEL_ALPHA = 0;
		/** <i>native declaration : jxl/codestream_header.h:26</i> */
		int JXL_CHANNEL_DEPTH = 1;
		/** <i>native declaration : jxl/codestream_header.h:27</i> */
		int JXL_CHANNEL_SPOT_COLOR = 2;
		/** <i>native declaration : jxl/codestream_header.h:28</i> */
		int JXL_CHANNEL_SELECTION_MASK = 3;
		/** <i>native declaration : jxl/codestream_header.h:29</i> */
		int JXL_CHANNEL_BLACK = 4;
		/** <i>native declaration : jxl/codestream_header.h:30</i> */
		int JXL_CHANNEL_CFA = 5;
		/** <i>native declaration : jxl/codestream_header.h:31</i> */
		int JXL_CHANNEL_THERMAL = 6;
		/** <i>native declaration : jxl/codestream_header.h:32</i> */
		int JXL_CHANNEL_RESERVED0 = 7;
		/** <i>native declaration : jxl/codestream_header.h:33</i> */
		int JXL_CHANNEL_RESERVED1 = 8;
		/** <i>native declaration : jxl/codestream_header.h:34</i> */
		int JXL_CHANNEL_RESERVED2 = 9;
		/** <i>native declaration : jxl/codestream_header.h:35</i> */
		int JXL_CHANNEL_RESERVED3 = 10;
		/** <i>native declaration : jxl/codestream_header.h:36</i> */
		int JXL_CHANNEL_RESERVED4 = 11;
		/** <i>native declaration : jxl/codestream_header.h:37</i> */
		int JXL_CHANNEL_RESERVED5 = 12;
		/** <i>native declaration : jxl/codestream_header.h:38</i> */
		int JXL_CHANNEL_RESERVED6 = 13;
		/** <i>native declaration : jxl/codestream_header.h:39</i> */
		int JXL_CHANNEL_RESERVED7 = 14;
		/** <i>native declaration : jxl/codestream_header.h:40</i> */
		int JXL_CHANNEL_UNKNOWN = 15;
		/** <i>native declaration : jxl/codestream_header.h:41</i> */
		int JXL_CHANNEL_OPTIONAL = 16;
	};
	/** <i>native declaration : jxl/types.h</i> */
	int JXL_TRUE = 1;
	/** <i>native declaration : jxl/types.h</i> */
	int JXL_FALSE = 0;
	/** <i>native declaration : jxl/parallel_runner.h</i> */
	int JXL_PARALLEL_RET_RUNNER_ERROR = -1;
	/** <i>native declaration : jxl/memory_manager.h</i> */
	public interface jpegxl_alloc_func extends Callback {
		Pointer apply(Pointer opaque, int size);
	}
	/** <i>native declaration : jxl/memory_manager.h</i> */
	public interface jpegxl_free_func extends Callback {
		void apply(Pointer opaque, Pointer address);
	}
	/** <i>native declaration : jxl/parallel_runner.h</i> */
	public interface JxlParallelRunInit extends Callback {
		int apply(Pointer jpegxl_opaque, int num_threads);
	}
	/** <i>native declaration : jxl/parallel_runner.h</i> */
	public interface JxlParallelRunFunction extends Callback {
		void apply(Pointer jpegxl_opaque, int value, int thread_id);
	}
	/** <i>native declaration : jxl/parallel_runner.h</i> */
	public interface JxlParallelRunner extends Callback {
		int apply(Pointer runner_opaque, Pointer jpegxl_opaque, Library.JxlParallelRunInit init, Library.JxlParallelRunFunction func, int start_range, int end_range);
	}
}
